FROM python:3.12-alpine

RUN apk add --no-cache build-base

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY spaceship/ spaceship/
COPY build/      build/

EXPOSE 8000
CMD ["uvicorn", "spaceship.main:app", "--host", "0.0.0.0", "--port", "8000"]
